// <auto-generated />
using System;
using Classics_Shop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Classics_Shop.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20210123184912_addingData")]
    partial class addingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Classics_Shop.Models.Arival", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(10000);

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("arivals");

                    b.HasData(
                        new
                        {
                            ID = 6,
                            Description = "296 calendar men's watch waterproof quartz watch is one of the most cool whatch to have in town. Buy one for yourself today.",
                            ImagePath = "whatch3.jpeg",
                            ProductName = "296 calendar men's watch waterproof quartz watch",
                            UnitPrice = 10000.0m
                        },
                        new
                        {
                            ID = 7,
                            Description = "Men watches casual sports watch is a waterproof quartz watch is one of the most cool whatch to have in town. Buy one for yourself today.",
                            ImagePath = "whatch4.jpeg",
                            ProductName = "Men watches casual sports watch",
                            UnitPrice = 14000.8m
                        },
                        new
                        {
                            ID = 8,
                            Description = "Business brogue suede dress shoes is affordable and clean shoe you wou;d like to have and enjoy it.",
                            ImagePath = "s1.jpeg",
                            ProductName = "Men fashion business brogue suede dress shoes",
                            UnitPrice = 20000.90m
                        },
                        new
                        {
                            ID = 9,
                            Description = "Men's Shoes Fall 2019 Sports Shoes Men's Fashion Leisure Shoes A Generic PU Small White Shoe",
                            ImagePath = "s2.jpeg",
                            ProductName = "Leisure Shoes",
                            UnitPrice = 20000.90m
                        });
                });

            modelBuilder.Entity("Classics_Shop.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Computer & Office"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Clothing"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Shoe"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Luggage & Bags"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Watch & Jewelry"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Home & Appliances"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Phones & Tel"
                        });
                });

            modelBuilder.Entity("Classics_Shop.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(10000);

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1,
                            Description = "sweet 2.4G Ultra Slim wireless keyboard Portable Mute Keys Keyboards mouse combos for Mac Win XP 7 wireless Keyboard and mouse",
                            ImagePath = "image1.jpeg",
                            ProductName = "Keyboards",
                            UnitPrice = 60000.779999999999
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 1,
                            Description = "Wireless Keyboard  Ultra Slim wireless keyboard Portable Mute Keys Keyboards mouse combos for Mac Win XP 7 wireless Keyboard and mouse",
                            ImagePath = "image12.jpeg",
                            ProductName = "Wireless Keyboard and Mouse Mini Multimedia",
                            UnitPrice = 70000.110000000001
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 5,
                            Description = "Get one of these whatch. You will love it. This will change your life style",
                            ImagePath = "whatch2.jpeg",
                            ProductName = "Simple Fashion Casual Business Watches",
                            UnitPrice = 30000.799999999999
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 5,
                            Description = "Get one of these whatch. You will love it. This will change your life style",
                            ImagePath = "whatch1.jpeg",
                            ProductName = "SKMEI Luxury Men Watch Fashion Casual Watches",
                            UnitPrice = 40000.0
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryID = 5,
                            Description = "296 calendar men's watch waterproof quartz watch is one of the most cool whatch to have in town. Buy one for yourself today.",
                            ImagePath = "whatch3.jpeg",
                            ProductName = "296 calendar men's watch waterproof quartz watch",
                            UnitPrice = 10000.0
                        },
                        new
                        {
                            ProductID = 7,
                            CategoryID = 5,
                            Description = "Men watches casual sports watch is a waterproof quartz watch is one of the most cool whatch to have in town. Buy one for yourself today.",
                            ImagePath = "whatch4.jpeg",
                            ProductName = "Men watches casual sports watch",
                            UnitPrice = 14000.799999999999
                        },
                        new
                        {
                            ProductID = 8,
                            CategoryID = 2,
                            Description = "Business brogue suede dress shoes is affordable and clean shoe you wou;d like to have and enjoy it.",
                            ImagePath = "s1.jpeg",
                            ProductName = "Men fashion business brogue suede dress shoes",
                            UnitPrice = 20000.900000000001
                        },
                        new
                        {
                            ProductID = 9,
                            CategoryID = 2,
                            Description = "Men's Shoes Fall 2019 Sports Shoes Men's Fashion Leisure Shoes A Generic PU Small White Shoe",
                            ImagePath = "s2.jpeg",
                            ProductName = "Leisure Shoes",
                            UnitPrice = 20000.900000000001
                        });
                });

            modelBuilder.Entity("Classics_Shop.Models.Arival", b =>
                {
                    b.HasOne("Classics_Shop.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID");
                });

            modelBuilder.Entity("Classics_Shop.Models.Product", b =>
                {
                    b.HasOne("Classics_Shop.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID");
                });
#pragma warning restore 612, 618
        }
    }
}
